INSERT INTO STUDENT (NAME, SUBJECT,COURSE) VALUES ('Dinesh', 'Java', 'Computer');
INSERT INTO STUDENT (NAME, SUBJECT,COURSE) VALUES ('Raj', 'Network', 'CCNA');
INSERT INTO STUDENT (NAME, SUBJECT,COURSE) VALUES ('Sam', 'E&TC', 'Embedded');